//! SeaORM Entity. Generated by sea-orm-codegen 0.8.0

pub use super::users::ActiveModel as UsersActiveModel;
pub use super::users::Column as UsersColumn;
pub use super::users::Entity as Users;
pub use super::users::Model as UsersModel;
